#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>
#include <cctype>
#include <sstream>

using Value = std::variant<long long, std::string, bool>;
enum class K { End, Num, Str, Name, Let, Print, If, Else, While, True, False, Lp, Rp, Lb, Rb, Semi, Plus, Minus, Star, Slash, Bang, Eq, EqEq, Ne, Lt, Le, Gt, Ge };
struct Token { K k; std::string s; int line; };

struct Lexer {
  std::string in; size_t p=0; int line=1;
  char take(){ return p<in.size()?in[p++]:0; } char peek(){ return p<in.size()?in[p]:0; }
  std::vector<Token> run() { std::vector<Token> v; for (;;) { while (std::isspace((unsigned char)peek())) { if(take()=='\n') ++line; } if(peek()=='/'&&p+1<in.size()&&in[p+1]=='/'){while(peek()&&peek()!='\n')take();continue;}
    int l=line; char c=take(); if(!c) { v.push_back({K::End,"",l}); return v; }
    if (std::isdigit((unsigned char)c)) { std::string s(1,c); while(std::isdigit((unsigned char)peek()))s+=take(); v.push_back({K::Num,s,l}); continue; }
    if (std::isalpha((unsigned char)c)||c=='_') { std::string s(1,c); while(std::isalnum((unsigned char)peek())||peek()=='_')s+=take();
      static std::map<std::string,K> keys={{"let",K::Let},{"print",K::Print},{"if",K::If},{"else",K::Else},{"while",K::While},{"true",K::True},{"false",K::False}}; v.push_back({keys.count(s)?keys[s]:K::Name,s,l}); continue; }
    if(c=='"') { std::string s; while(peek()&&peek()!='"') { char x=take(); if(x=='\\') { x=take(); if(x=='n') x='\n'; } s+=x; } if(!take()) throw std::runtime_error("unterminated string at line "+std::to_string(l)); v.push_back({K::Str,s,l}); continue; }
    auto one=[&](K k){v.push_back({k,"",l});}; switch(c) { case '(':one(K::Lp);break;case ')':one(K::Rp);break;case '{':one(K::Lb);break;case '}':one(K::Rb);break;case ';':one(K::Semi);break;case '+':one(K::Plus);break;case '-':one(K::Minus);break;case '*':one(K::Star);break;case '/':one(K::Slash);break;case '!': if(peek()=='='){take();one(K::Ne);}else one(K::Bang);break;case '=':if(peek()=='='){take();one(K::EqEq);}else one(K::Eq);break;case '<':if(peek()=='='){take();one(K::Le);}else one(K::Lt);break;case '>':if(peek()=='='){take();one(K::Ge);}else one(K::Gt);break; default: throw std::runtime_error("unexpected character at line "+std::to_string(l)); }
  }}
};

enum class Op : uint8_t { Int, Str, Bool, Load, Store, Add, Sub, Mul, Div, Neg, Not, Eq, Ne, Lt, Le, Gt, Ge, Print, Pop, Jz, Jump, Halt };
struct Ins { Op op; long long n=0; std::string s; };
struct Parser { std::vector<Token> t; size_t p=0; std::vector<Ins> code;
  Token& cur(){return t[p];} bool is(K k){return cur().k==k;} bool eat(K k){if(is(k)){++p;return true;}return false;} void need(K k,const char* what){if(!eat(k))throw std::runtime_error(std::string("expected ")+what+" at line "+std::to_string(cur().line));} int emit(Op o,long long n=0,std::string s={}){code.push_back({o,n,s});return (int)code.size()-1;}
  void program(){while(!is(K::End)) stmt();emit(Op::Halt);} void stmt(){ if(eat(K::Let)){std::string n=cur().s;need(K::Name,"variable name");need(K::Eq,"=");expr();need(K::Semi,";");emit(Op::Store,0,n);}
    else if(eat(K::Print)){expr();need(K::Semi,";");emit(Op::Print);} else if(eat(K::Lb)){while(!eat(K::Rb)) {if(is(K::End))throw std::runtime_error("unclosed block");stmt();}}
    else if(eat(K::If)){need(K::Lp,"(");expr();need(K::Rp,")");int no=emit(Op::Jz);stmt();if(eat(K::Else)){int end=emit(Op::Jump);code[no].n=code.size();stmt();code[end].n=code.size();}else code[no].n=code.size();}
    else if(eat(K::While)){int start=code.size();need(K::Lp,"(");expr();need(K::Rp,")");int end=emit(Op::Jz);stmt();emit(Op::Jump,start);code[end].n=code.size();}
    else if(is(K::Name)&&p+1<t.size()&&t[p+1].k==K::Eq){std::string n=cur().s;p+=2;expr();need(K::Semi,";");emit(Op::Store,0,n);} else {expr();need(K::Semi,";");emit(Op::Pop);} }
  void expr(){eq();} void eq(){cmp();while(is(K::EqEq)||is(K::Ne)){K k=cur().k;++p;cmp();emit(k==K::EqEq?Op::Eq:Op::Ne);}} void cmp(){term();while(is(K::Lt)||is(K::Le)||is(K::Gt)||is(K::Ge)){K k=cur().k;++p;term();emit(k==K::Lt?Op::Lt:k==K::Le?Op::Le:k==K::Gt?Op::Gt:Op::Ge);}} void term(){factor();while(is(K::Plus)||is(K::Minus)){K k=cur().k;++p;factor();emit(k==K::Plus?Op::Add:Op::Sub);}} void factor(){unary();while(is(K::Star)||is(K::Slash)){K k=cur().k;++p;unary();emit(k==K::Star?Op::Mul:Op::Div);}} void unary(){if(eat(K::Minus)){unary();emit(Op::Neg);}else if(eat(K::Bang)){unary();emit(Op::Not);}else primary();}
  void primary(){if(is(K::Num)){emit(Op::Int,std::stoll(cur().s));++p;}else if(is(K::Str)){emit(Op::Str,0,cur().s);++p;}else if(eat(K::True))emit(Op::Bool,1);else if(eat(K::False))emit(Op::Bool,0);else if(is(K::Name)){emit(Op::Load,0,cur().s);++p;}else if(eat(K::Lp)){expr();need(K::Rp,")");}else throw std::runtime_error("expected expression at line "+std::to_string(cur().line));}
};

static bool truth(const Value& v){if(auto x=std::get_if<bool>(&v))return *x;if(auto x=std::get_if<long long>(&v))return *x!=0;return !std::get<std::string>(v).empty();} static std::string show(const Value& v){if(auto x=std::get_if<long long>(&v))return std::to_string(*x);if(auto x=std::get_if<bool>(&v))return *x?"true":"false";return std::get<std::string>(v);} static long long integer(const Value& v){if(auto x=std::get_if<long long>(&v))return *x;throw std::runtime_error("integer required");}
void run(const std::vector<Ins>& c){std::vector<Value>s;std::map<std::string,Value> vars;auto pop=[&](){if(s.empty())throw std::runtime_error("stack underflow");Value x=s.back();s.pop_back();return x;};for(size_t ip=0;ip<c.size();++ip){auto&i=c[ip];switch(i.op){case Op::Int:s.push_back(i.n);break;case Op::Str:s.push_back(i.s);break;case Op::Bool:s.push_back(bool(i.n));break;case Op::Load:if(!vars.count(i.s))throw std::runtime_error("undefined variable: "+i.s);s.push_back(vars[i.s]);break;case Op::Store:vars[i.s]=pop();break;case Op::Add:{auto b=pop(),a=pop();if(a.index()==1||b.index()==1)s.push_back(show(a)+show(b));else s.push_back(integer(a)+integer(b));break;}case Op::Sub:{auto b=integer(pop()),a=integer(pop());s.push_back(a-b);break;}case Op::Mul:{auto b=integer(pop()),a=integer(pop());s.push_back(a*b);break;}case Op::Div:{auto b=integer(pop()),a=integer(pop());if(!b)throw std::runtime_error("division by zero");s.push_back(a/b);break;}case Op::Neg:s.push_back(-integer(pop()));break;case Op::Not:s.push_back(!truth(pop()));break;case Op::Eq:{auto b=pop(),a=pop();s.push_back(a==b);break;}case Op::Ne:{auto b=pop(),a=pop();s.push_back(a!=b);break;}case Op::Lt:{auto b=integer(pop()),a=integer(pop());s.push_back(a<b);break;}case Op::Le:{auto b=integer(pop()),a=integer(pop());s.push_back(a<=b);break;}case Op::Gt:{auto b=integer(pop()),a=integer(pop());s.push_back(a>b);break;}case Op::Ge:{auto b=integer(pop()),a=integer(pop());s.push_back(a>=b);break;}case Op::Print:std::cout<<show(pop())<<'\n';break;case Op::Pop:pop();break;case Op::Jz:if(!truth(pop()))ip=i.n-1;break;case Op::Jump:ip=i.n-1;break;case Op::Halt:return;}}}
void putstr(std::ostream&o,const std::string&s){uint32_t n=(uint32_t)s.size();o.write((char*)&n,4);o.write(s.data(),n);}std::string getstr(std::istream&i){uint32_t n;i.read((char*)&n,4);std::string s(n,' ');i.read(s.data(),n);return s;}void writecode(std::ostream&o,const std::vector<Ins>&c){o.write("TENN\1",5);uint32_t n=c.size();o.write((char*)&n,4);for(auto&i:c){auto op=(uint8_t)i.op;o.write((char*)&op,1);o.write((char*)&i.n,8);putstr(o,i.s);}}std::vector<Ins> readcode(std::istream&i){char h[5];i.read(h,5);if(std::string(h,5)!="TENN\1")throw std::runtime_error("not a Tennin bytecode file");uint32_t n;i.read((char*)&n,4);std::vector<Ins>c;while(n--){uint8_t o;long long x;i.read((char*)&o,1);i.read((char*)&x,8);c.push_back({(Op)o,x,getstr(i)});}return c;}void save(const std::string&f,const std::vector<Ins>&c){std::ofstream o(f,std::ios::binary);writecode(o,c);}std::vector<Ins> load(const std::string&f){std::ifstream i(f,std::ios::binary);return readcode(i);}void pack(const std::string&self,const std::string&out,const std::vector<Ins>&c){std::ifstream exe(self,std::ios::binary);std::ofstream o(out,std::ios::binary);o<<exe.rdbuf();std::ostringstream b(std::ios::binary);writecode(b,c);auto bytes=b.str();o.write(bytes.data(),bytes.size());uint64_t n=bytes.size();o.write((char*)&n,8);o.write("TNPKv001",8);}std::vector<Ins> packed(const std::string&f){std::ifstream i(f,std::ios::binary);i.seekg(0,std::ios::end);auto end=i.tellg();if(end<16)throw std::runtime_error("not a packed Tennin file");i.seekg(end-std::streamoff(8));char m[8];i.read(m,8);if(std::string(m,8)!="TNPKv001")throw std::runtime_error("not a packed Tennin file");i.seekg(end-std::streamoff(16));uint64_t n;i.read((char*)&n,8);i.seekg(end-std::streamoff(16)-std::streamoff(n));return readcode(i);}
int main(int argc,char**argv){try{if(argc==1){run(packed(argv[0]));return 0;}std::string input=argv[1];if(argc==2&&input.ends_with(".tennbc")){run(load(input));return 0;}bool output=argc==4&&std::string(argv[2])=="-o";bool packing=argc==4&&input=="--pack";if(!(argc==2||output||packing))throw std::runtime_error("usage: tenn program.tenn [-o program.tennbc] | tenn program.tennbc | tenn --pack source.tenn output.tenn");std::string src=packing?argv[2]:input;std::ifstream f(src);if(!f)throw std::runtime_error("cannot open: "+src);std::string text((std::istreambuf_iterator<char>(f)),{});Parser p{Lexer{text}.run()};p.program();if(packing)pack(argv[0],argv[3],p.code);else if(output)save(argv[3],p.code);else run(p.code);}catch(const std::exception&e){std::cerr<<"tenn: "<<e.what()<<'\n';return 1;}}
